//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accolades
    {
        public int Accolade_PK { get; set; }
        public int Accolade_Point_Value { get; set; }
        public string Accolade_Description { get; set; }
    }
}
