//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign_to_Character
    {
        public int EF_PK { get; set; }
        public int Campaign_FK { get; set; }
        public int Character_FK { get; set; }
        public int Remaining_Energy { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
    }
}
