//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public Campaigns()
        {
            this.Campaign_to_Character = new HashSet<Campaign_to_Character>();
            this.Skirmishes = new HashSet<Skirmishes>();
        }
    
        public int Campaign_PK { get; set; }
        public System.DateTime Campaign_Start_Date { get; set; }
        public Nullable<System.DateTime> Campaign_End_Date { get; set; }
        public int Series_FK { get; set; }
        public bool bIsLive { get; set; }
    
        public virtual ICollection<Campaign_to_Character> Campaign_to_Character { get; set; }
        public virtual Series Series { get; set; }
        public virtual ICollection<Skirmishes> Skirmishes { get; set; }
    }
}
