//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character_Track_Log
    {
        public int CharTrackLog_PK { get; set; }
        public int Character_FK { get; set; }
        public int Damage_Dealt { get; set; }
        public int Damage_Taken { get; set; }
        public int Opponent_Knock_Outs { get; set; }
        public int Self_Knock_Outs { get; set; }
        public int Assist_Knock_Outs { get; set; }
        public int Attacks_Dodged { get; set; }
        public int Critical_Successes { get; set; }
        public int Critical_Fails { get; set; }
        public int Series_Participated { get; set; }
        public int Skirmishes_Participated { get; set; }
        public int Health_Regained { get; set; }
        public int Skirmishes_Survived { get; set; }
        public int Ally_Bonus_Damage { get; set; }
        public int Enemy_Less_Damage { get; set; }
        public int Afflictions_Inflicted { get; set; }
        public int Initiative_Acted_First { get; set; }
        public int Series_FK { get; set; }
    
        public virtual Series Series { get; set; }
    }
}
