//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combat_Logs
    {
        public int CombatLog_PK { get; set; }
        public int Assailant_Character_FK { get; set; }
        public int Target_Character_FK { get; set; }
        public int Skill_FK { get; set; }
        public int Attack_Final_Result { get; set; }
        public string Attack_Values { get; set; }
        public int Damage_Final_Result { get; set; }
        public string Damage_Values { get; set; }
        public int Conditions { get; set; }
    
        public virtual Skills Skills { get; set; }
    }
}
