//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentWorkflowSources
    {
        public int SourceID { get; set; }
        public int WorkflowID { get; set; }
        public string SourceName { get; set; }
        public string SourceType { get; set; }
    
        public virtual ContentWorkflows ContentWorkflows { get; set; }
    }
}
