//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentWorkflowActions
    {
        public int ActionId { get; set; }
        public int ContentTypeId { get; set; }
        public string ActionType { get; set; }
        public string ActionSource { get; set; }
    
        public virtual ContentTypes ContentTypes { get; set; }
    }
}
