//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTypes
    {
        public ContentTypes()
        {
            this.ContentItems = new HashSet<ContentItems>();
            this.ContentWorkflowActions = new HashSet<ContentWorkflowActions>();
        }
    
        public int ContentTypeID { get; set; }
        public string ContentType { get; set; }
    
        public virtual ICollection<ContentItems> ContentItems { get; set; }
        public virtual ICollection<ContentWorkflowActions> ContentWorkflowActions { get; set; }
    }
}
