//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft_Table
    {
        public int EF_PK { get; set; }
        public string User_FK { get; set; }
        public int League_FK { get; set; }
        public int Character_FK { get; set; }
        public int Char_Accolade_Points_For_User { get; set; }
    
        public virtual Leagues Leagues { get; set; }
    }
}
