//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionEvents
    {
        public long LogEventID { get; set; }
        public string AssemblyVersion { get; set; }
        public Nullable<int> PortalId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TabId { get; set; }
        public string RawUrl { get; set; }
        public string Referrer { get; set; }
        public string UserAgent { get; set; }
    
        public virtual EventLog EventLog { get; set; }
    }
}
