//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folders
    {
        public Folders()
        {
            this.Files = new HashSet<Files>();
            this.FolderPermission = new HashSet<FolderPermission>();
        }
    
        public int FolderID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string FolderPath { get; set; }
        public int StorageLocation { get; set; }
        public bool IsProtected { get; set; }
        public bool IsCached { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public System.Guid UniqueId { get; set; }
        public System.Guid VersionGuid { get; set; }
        public int FolderMappingID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsVersioned { get; set; }
        public Nullable<int> WorkflowID { get; set; }
        public string MappedPath { get; set; }
    
        public virtual ContentWorkflows ContentWorkflows { get; set; }
        public virtual ICollection<Files> Files { get; set; }
        public virtual FolderMappings FolderMappings { get; set; }
        public virtual ICollection<FolderPermission> FolderPermission { get; set; }
        public virtual Portals Portals { get; set; }
    }
}
