//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guilds
    {
        public Guilds()
        {
            this.Characters = new HashSet<Characters>();
            this.Skirmishes = new HashSet<Skirmishes>();
            this.Skirmishes1 = new HashSet<Skirmishes>();
        }
    
        public int Guild_PK { get; set; }
        public string Guild_Name { get; set; }
    
        public virtual ICollection<Characters> Characters { get; set; }
        public virtual ICollection<Skirmishes> Skirmishes { get; set; }
        public virtual ICollection<Skirmishes> Skirmishes1 { get; set; }
    }
}
