//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leagues
    {
        public Leagues()
        {
            this.Draft_Table = new HashSet<Draft_Table>();
            this.League_to_User = new HashSet<League_to_User>();
        }
    
        public int League_PK { get; set; }
        public int League_Type { get; set; }
        public string League_Name { get; set; }
        public string League_Description { get; set; }
        public bool Trade_Day_Enabled { get; set; }
    
        public virtual ICollection<Draft_Table> Draft_Table { get; set; }
        public virtual ICollection<League_to_User> League_to_User { get; set; }
    }
}
