//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageTypes
    {
        public PackageTypes()
        {
            this.Packages = new HashSet<Packages>();
        }
    
        public string PackageType { get; set; }
        public string Description { get; set; }
        public int SecurityAccessLevel { get; set; }
        public string EditorControlSrc { get; set; }
        public bool SupportsSideBySideInstallation { get; set; }
    
        public virtual ICollection<Packages> Packages { get; set; }
    }
}
