//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalDesktopModules
    {
        public PortalDesktopModules()
        {
            this.DesktopModulePermission = new HashSet<DesktopModulePermission>();
        }
    
        public int PortalDesktopModuleID { get; set; }
        public int PortalID { get; set; }
        public int DesktopModuleID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual ICollection<DesktopModulePermission> DesktopModulePermission { get; set; }
        public virtual DesktopModules DesktopModules { get; set; }
        public virtual Portals Portals { get; set; }
    }
}
