//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portals
    {
        public Portals()
        {
            this.AnonymousUsers = new HashSet<AnonymousUsers>();
            this.CoreMessaging_Subscriptions = new HashSet<CoreMessaging_Subscriptions>();
            this.Files = new HashSet<Files>();
            this.FolderMappings = new HashSet<FolderMappings>();
            this.Folders = new HashSet<Folders>();
            this.Mobile_PreviewProfiles = new HashSet<Mobile_PreviewProfiles>();
            this.Mobile_Redirections = new HashSet<Mobile_Redirections>();
            this.PortalAlias = new HashSet<PortalAlias>();
            this.PortalDesktopModules = new HashSet<PortalDesktopModules>();
            this.PortalLanguages = new HashSet<PortalLanguages>();
            this.PortalLocalization = new HashSet<PortalLocalization>();
            this.PortalSettings = new HashSet<PortalSettings>();
            this.Profile = new HashSet<Profile>();
            this.ProfilePropertyDefinition = new HashSet<ProfilePropertyDefinition>();
            this.Relationships = new HashSet<Relationships>();
            this.RoleGroups = new HashSet<RoleGroups>();
            this.Roles = new HashSet<Roles>();
            this.SiteLog = new HashSet<SiteLog>();
            this.SystemMessages = new HashSet<SystemMessages>();
            this.Tabs = new HashSet<Tabs>();
            this.Urls = new HashSet<Urls>();
            this.UrlTracking = new HashSet<UrlTracking>();
            this.UserPortals = new HashSet<UserPortals>();
            this.UsersOnline = new HashSet<UsersOnline>();
            this.Vendors = new HashSet<Vendors>();
        }
    
        public int PortalID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int UserRegistration { get; set; }
        public int BannerAdvertising { get; set; }
        public Nullable<int> AdministratorId { get; set; }
        public string Currency { get; set; }
        public decimal HostFee { get; set; }
        public int HostSpace { get; set; }
        public Nullable<int> AdministratorRoleId { get; set; }
        public Nullable<int> RegisteredRoleId { get; set; }
        public System.Guid GUID { get; set; }
        public string PaymentProcessor { get; set; }
        public string ProcessorUserId { get; set; }
        public string ProcessorPassword { get; set; }
        public Nullable<int> SiteLogHistory { get; set; }
        public string DefaultLanguage { get; set; }
        public int TimezoneOffset { get; set; }
        public string HomeDirectory { get; set; }
        public int PageQuota { get; set; }
        public int UserQuota { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> PortalGroupID { get; set; }
    
        public virtual ICollection<AnonymousUsers> AnonymousUsers { get; set; }
        public virtual ICollection<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual ICollection<Files> Files { get; set; }
        public virtual ICollection<FolderMappings> FolderMappings { get; set; }
        public virtual ICollection<Folders> Folders { get; set; }
        public virtual ICollection<Mobile_PreviewProfiles> Mobile_PreviewProfiles { get; set; }
        public virtual ICollection<Mobile_Redirections> Mobile_Redirections { get; set; }
        public virtual ICollection<PortalAlias> PortalAlias { get; set; }
        public virtual ICollection<PortalDesktopModules> PortalDesktopModules { get; set; }
        public virtual ICollection<PortalLanguages> PortalLanguages { get; set; }
        public virtual ICollection<PortalLocalization> PortalLocalization { get; set; }
        public virtual ICollection<PortalSettings> PortalSettings { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<ProfilePropertyDefinition> ProfilePropertyDefinition { get; set; }
        public virtual ICollection<Relationships> Relationships { get; set; }
        public virtual ICollection<RoleGroups> RoleGroups { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
        public virtual ICollection<SiteLog> SiteLog { get; set; }
        public virtual ICollection<SystemMessages> SystemMessages { get; set; }
        public virtual ICollection<Tabs> Tabs { get; set; }
        public virtual ICollection<Urls> Urls { get; set; }
        public virtual ICollection<UrlTracking> UrlTracking { get; set; }
        public virtual ICollection<UserPortals> UserPortals { get; set; }
        public virtual ICollection<UsersOnline> UsersOnline { get; set; }
        public virtual ICollection<Vendors> Vendors { get; set; }
    }
}
