//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationships
    {
        public Relationships()
        {
            this.UserRelationshipPreferences = new HashSet<UserRelationshipPreferences>();
            this.UserRelationships = new HashSet<UserRelationships>();
        }
    
        public int RelationshipID { get; set; }
        public int RelationshipTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int DefaultResponse { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual Portals Portals { get; set; }
        public virtual RelationshipTypes RelationshipTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<UserRelationshipPreferences> UserRelationshipPreferences { get; set; }
        public virtual ICollection<UserRelationships> UserRelationships { get; set; }
    }
}
