//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipTypes
    {
        public RelationshipTypes()
        {
            this.Relationships = new HashSet<Relationships>();
        }
    
        public int RelationshipTypeID { get; set; }
        public int Direction { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual ICollection<Relationships> Relationships { get; set; }
    }
}
