//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class RPGFLEntities : DbContext
{
    public RPGFLEntities()
        : base("name=RPGFLEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Affiliates> Affiliates { get; set; }
    public virtual DbSet<AnonymousUsers> AnonymousUsers { get; set; }
    public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
    public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
    public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
    public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
    public virtual DbSet<Assemblies> Assemblies { get; set; }
    public virtual DbSet<Authentication> Authentication { get; set; }
    public virtual DbSet<Banners> Banners { get; set; }
    public virtual DbSet<Campaign_to_Character> Campaign_to_Character { get; set; }
    public virtual DbSet<Campaigns> Campaigns { get; set; }
    public virtual DbSet<Character_to_Series> Character_to_Series { get; set; }
    public virtual DbSet<Character_to_Skill> Character_to_Skill { get; set; }
    public virtual DbSet<Character_to_Skirmish> Character_to_Skirmish { get; set; }
    public virtual DbSet<Character_Track_Log> Character_Track_Log { get; set; }
    public virtual DbSet<Characters> Characters { get; set; }
    public virtual DbSet<Classification> Classification { get; set; }
    public virtual DbSet<Conditions> Conditions { get; set; }
    public virtual DbSet<ContentItems> ContentItems { get; set; }
    public virtual DbSet<ContentItems_MetaData> ContentItems_MetaData { get; set; }
    public virtual DbSet<ContentItems_Tags> ContentItems_Tags { get; set; }
    public virtual DbSet<ContentTypes> ContentTypes { get; set; }
    public virtual DbSet<ContentWorkflowActions> ContentWorkflowActions { get; set; }
    public virtual DbSet<ContentWorkflowLogs> ContentWorkflowLogs { get; set; }
    public virtual DbSet<ContentWorkflows> ContentWorkflows { get; set; }
    public virtual DbSet<ContentWorkflowSources> ContentWorkflowSources { get; set; }
    public virtual DbSet<ContentWorkflowStatePermission> ContentWorkflowStatePermission { get; set; }
    public virtual DbSet<ContentWorkflowStates> ContentWorkflowStates { get; set; }
    public virtual DbSet<CoreMessaging_MessageAttachments> CoreMessaging_MessageAttachments { get; set; }
    public virtual DbSet<CoreMessaging_MessageRecipients> CoreMessaging_MessageRecipients { get; set; }
    public virtual DbSet<CoreMessaging_Messages> CoreMessaging_Messages { get; set; }
    public virtual DbSet<CoreMessaging_NotificationTypeActions> CoreMessaging_NotificationTypeActions { get; set; }
    public virtual DbSet<CoreMessaging_NotificationTypes> CoreMessaging_NotificationTypes { get; set; }
    public virtual DbSet<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
    public virtual DbSet<CoreMessaging_SubscriptionTypes> CoreMessaging_SubscriptionTypes { get; set; }
    public virtual DbSet<CoreMessaging_UserPreferences> CoreMessaging_UserPreferences { get; set; }
    public virtual DbSet<Damage_Types> Damage_Types { get; set; }
    public virtual DbSet<Dashboard_Controls> Dashboard_Controls { get; set; }
    public virtual DbSet<DesktopModulePermission> DesktopModulePermission { get; set; }
    public virtual DbSet<DesktopModules> DesktopModules { get; set; }
    public virtual DbSet<Draft_Table> Draft_Table { get; set; }
    public virtual DbSet<EventLog> EventLog { get; set; }
    public virtual DbSet<EventLogConfig> EventLogConfig { get; set; }
    public virtual DbSet<EventLogTypes> EventLogTypes { get; set; }
    public virtual DbSet<EventQueue> EventQueue { get; set; }
    public virtual DbSet<ExceptionEvents> ExceptionEvents { get; set; }
    public virtual DbSet<Exceptions> Exceptions { get; set; }
    public virtual DbSet<ExtensionUrlProviderConfiguration> ExtensionUrlProviderConfiguration { get; set; }
    public virtual DbSet<ExtensionUrlProviders> ExtensionUrlProviders { get; set; }
    public virtual DbSet<ExtensionUrlProviderSetting> ExtensionUrlProviderSetting { get; set; }
    public virtual DbSet<ExtensionUrlProviderTab> ExtensionUrlProviderTab { get; set; }
    public virtual DbSet<Files> Files { get; set; }
    public virtual DbSet<FileVersions> FileVersions { get; set; }
    public virtual DbSet<FolderMappings> FolderMappings { get; set; }
    public virtual DbSet<FolderMappingsSettings> FolderMappingsSettings { get; set; }
    public virtual DbSet<FolderPermission> FolderPermission { get; set; }
    public virtual DbSet<Folders> Folders { get; set; }
    public virtual DbSet<Guilds> Guilds { get; set; }
    public virtual DbSet<HostSettings> HostSettings { get; set; }
    public virtual DbSet<HtmlText> HtmlText { get; set; }
    public virtual DbSet<HtmlTextLog> HtmlTextLog { get; set; }
    public virtual DbSet<HtmlTextUsers> HtmlTextUsers { get; set; }
    public virtual DbSet<IPFilter> IPFilter { get; set; }
    public virtual DbSet<JavaScriptLibraries> JavaScriptLibraries { get; set; }
    public virtual DbSet<Journal> Journal { get; set; }
    public virtual DbSet<Journal_Access> Journal_Access { get; set; }
    public virtual DbSet<Journal_Comments> Journal_Comments { get; set; }
    public virtual DbSet<Journal_Data> Journal_Data { get; set; }
    public virtual DbSet<Journal_Security> Journal_Security { get; set; }
    public virtual DbSet<Journal_TypeFilters> Journal_TypeFilters { get; set; }
    public virtual DbSet<Journal_Types> Journal_Types { get; set; }
    public virtual DbSet<LanguagePacks> LanguagePacks { get; set; }
    public virtual DbSet<Languages> Languages { get; set; }
    public virtual DbSet<League_to_User> League_to_User { get; set; }
    public virtual DbSet<Leagues> Leagues { get; set; }
    public virtual DbSet<Lists> Lists { get; set; }
    public virtual DbSet<Messaging_Messages> Messaging_Messages { get; set; }
    public virtual DbSet<MetaData> MetaData { get; set; }
    public virtual DbSet<Mobile_PreviewProfiles> Mobile_PreviewProfiles { get; set; }
    public virtual DbSet<Mobile_RedirectionRules> Mobile_RedirectionRules { get; set; }
    public virtual DbSet<Mobile_Redirections> Mobile_Redirections { get; set; }
    public virtual DbSet<ModuleControls> ModuleControls { get; set; }
    public virtual DbSet<ModuleDefinitions> ModuleDefinitions { get; set; }
    public virtual DbSet<ModulePermission> ModulePermission { get; set; }
    public virtual DbSet<Modules> Modules { get; set; }
    public virtual DbSet<ModuleSettings> ModuleSettings { get; set; }
    public virtual DbSet<PackageDependencies> PackageDependencies { get; set; }
    public virtual DbSet<Packages> Packages { get; set; }
    public virtual DbSet<PackageTypes> PackageTypes { get; set; }
    public virtual DbSet<PasswordHistory> PasswordHistory { get; set; }
    public virtual DbSet<Permission> Permission { get; set; }
    public virtual DbSet<PortalAlias> PortalAlias { get; set; }
    public virtual DbSet<PortalDesktopModules> PortalDesktopModules { get; set; }
    public virtual DbSet<PortalGroups> PortalGroups { get; set; }
    public virtual DbSet<PortalLanguages> PortalLanguages { get; set; }
    public virtual DbSet<PortalLocalization> PortalLocalization { get; set; }
    public virtual DbSet<Portals> Portals { get; set; }
    public virtual DbSet<PortalSettings> PortalSettings { get; set; }
    public virtual DbSet<Profile> Profile { get; set; }
    public virtual DbSet<ProfilePropertyDefinition> ProfilePropertyDefinition { get; set; }
    public virtual DbSet<Relationships> Relationships { get; set; }
    public virtual DbSet<RelationshipTypes> RelationshipTypes { get; set; }
    public virtual DbSet<RoleGroups> RoleGroups { get; set; }
    public virtual DbSet<Roles> Roles { get; set; }
    public virtual DbSet<RoleSettings> RoleSettings { get; set; }
    public virtual DbSet<Schedule> Schedule { get; set; }
    public virtual DbSet<ScheduleHistory> ScheduleHistory { get; set; }
    public virtual DbSet<ScheduleItemSettings> ScheduleItemSettings { get; set; }
    public virtual DbSet<SearchCommonWords> SearchCommonWords { get; set; }
    public virtual DbSet<SearchDeletedItems> SearchDeletedItems { get; set; }
    public virtual DbSet<SearchIndexer> SearchIndexer { get; set; }
    public virtual DbSet<SearchStopWords> SearchStopWords { get; set; }
    public virtual DbSet<SearchTypes> SearchTypes { get; set; }
    public virtual DbSet<Series> Series { get; set; }
    public virtual DbSet<SiteLog> SiteLog { get; set; }
    public virtual DbSet<Skills> Skills { get; set; }
    public virtual DbSet<SkinControls> SkinControls { get; set; }
    public virtual DbSet<SkinPackages> SkinPackages { get; set; }
    public virtual DbSet<Skins> Skins { get; set; }
    public virtual DbSet<Skirmishes> Skirmishes { get; set; }
    public virtual DbSet<SQLQueries> SQLQueries { get; set; }
    public virtual DbSet<SynonymsGroups> SynonymsGroups { get; set; }
    public virtual DbSet<SystemMessages> SystemMessages { get; set; }
    public virtual DbSet<TabAliasSkins> TabAliasSkins { get; set; }
    public virtual DbSet<TabModules> TabModules { get; set; }
    public virtual DbSet<TabModuleSettings> TabModuleSettings { get; set; }
    public virtual DbSet<TabPermission> TabPermission { get; set; }
    public virtual DbSet<Tabs> Tabs { get; set; }
    public virtual DbSet<TabSettings> TabSettings { get; set; }
    public virtual DbSet<TabUrls> TabUrls { get; set; }
    public virtual DbSet<TabVersionDetails> TabVersionDetails { get; set; }
    public virtual DbSet<TabVersions> TabVersions { get; set; }
    public virtual DbSet<Taxonomy_ScopeTypes> Taxonomy_ScopeTypes { get; set; }
    public virtual DbSet<Taxonomy_Terms> Taxonomy_Terms { get; set; }
    public virtual DbSet<Taxonomy_Vocabularies> Taxonomy_Vocabularies { get; set; }
    public virtual DbSet<Taxonomy_VocabularyTypes> Taxonomy_VocabularyTypes { get; set; }
    public virtual DbSet<UrlLog> UrlLog { get; set; }
    public virtual DbSet<Urls> Urls { get; set; }
    public virtual DbSet<UrlTracking> UrlTracking { get; set; }
    public virtual DbSet<UserAuthentication> UserAuthentication { get; set; }
    public virtual DbSet<UserPortals> UserPortals { get; set; }
    public virtual DbSet<UserProfile> UserProfile { get; set; }
    public virtual DbSet<UserRelationshipPreferences> UserRelationshipPreferences { get; set; }
    public virtual DbSet<UserRelationships> UserRelationships { get; set; }
    public virtual DbSet<UserRoles> UserRoles { get; set; }
    public virtual DbSet<Users> Users { get; set; }
    public virtual DbSet<UsersOnline> UsersOnline { get; set; }
    public virtual DbSet<VendorClassification> VendorClassification { get; set; }
    public virtual DbSet<Vendors> Vendors { get; set; }
    public virtual DbSet<Version> Version { get; set; }
    public virtual DbSet<Votes> Votes { get; set; }
    public virtual DbSet<WebServers> WebServers { get; set; }
    public virtual DbSet<Workflow> Workflow { get; set; }
    public virtual DbSet<WorkflowStates> WorkflowStates { get; set; }
    public virtual DbSet<Combat_Logs> Combat_Logs { get; set; }
    public virtual DbSet<Accolades> Accolades { get; set; }
}
