//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchDeletedItems
    {
        public int SearchDeletedItemsID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Document { get; set; }
    }
}
