//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        public Series()
        {
            this.Campaigns = new HashSet<Campaigns>();
            this.Character_to_Series = new HashSet<Character_to_Series>();
            this.Character_Track_Log = new HashSet<Character_Track_Log>();
        }
    
        public int Series_PK { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public bool bIsLive { get; set; }
    
        public virtual ICollection<Campaigns> Campaigns { get; set; }
        public virtual ICollection<Character_to_Series> Character_to_Series { get; set; }
        public virtual ICollection<Character_Track_Log> Character_Track_Log { get; set; }
    }
}
