//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public Skills()
        {
            this.Character_to_Skill = new HashSet<Character_to_Skill>();
            this.Combat_Logs = new HashSet<Combat_Logs>();
            this.Votes = new HashSet<Votes>();
        }
    
        public int Skill_PK { get; set; }
        public string Skill_Name { get; set; }
        public string Skill_Description { get; set; }
        public int Energy_Cost { get; set; }
        public string Attribute_FK { get; set; }
        public bool bIsPassive { get; set; }
    
        public virtual ICollection<Character_to_Skill> Character_to_Skill { get; set; }
        public virtual ICollection<Combat_Logs> Combat_Logs { get; set; }
        public virtual ICollection<Votes> Votes { get; set; }
    }
}
