//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skirmishes
    {
        public Skirmishes()
        {
            this.Character_to_Skirmish = new HashSet<Character_to_Skirmish>();
            this.Votes = new HashSet<Votes>();
        }
    
        public int Skirmish_PK { get; set; }
        public System.DateTime Skirmish_Date { get; set; }
        public int Campaign_FK { get; set; }
        public int Guild_1_FK { get; set; }
        public int Guild_2_FK { get; set; }
        public int Guild_1_Accolade_Points { get; set; }
        public int Guild_2_Accolade_Points { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
        public virtual ICollection<Character_to_Skirmish> Character_to_Skirmish { get; set; }
        public virtual Guilds Guilds { get; set; }
        public virtual Guilds Guilds1 { get; set; }
        public virtual ICollection<Votes> Votes { get; set; }
    }
}
