//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabVersionDetails
    {
        public int TabVersionDetailId { get; set; }
        public int TabVersionId { get; set; }
        public int ModuleId { get; set; }
        public int ModuleVersion { get; set; }
        public string PaneName { get; set; }
        public int ModuleOrder { get; set; }
        public int Action { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual TabVersions TabVersions { get; set; }
    }
}
