//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.ContentWorkflowStatePermission = new HashSet<ContentWorkflowStatePermission>();
            this.CoreMessaging_Subscriptions = new HashSet<CoreMessaging_Subscriptions>();
            this.DesktopModulePermission = new HashSet<DesktopModulePermission>();
            this.FolderPermission = new HashSet<FolderPermission>();
            this.ModulePermission = new HashSet<ModulePermission>();
            this.PasswordHistory = new HashSet<PasswordHistory>();
            this.Profile = new HashSet<Profile>();
            this.Relationships = new HashSet<Relationships>();
            this.TabPermission = new HashSet<TabPermission>();
            this.UserAuthentication = new HashSet<UserAuthentication>();
            this.UserPortals = new HashSet<UserPortals>();
            this.UserProfile = new HashSet<UserProfile>();
            this.UserRelationshipPreferences = new HashSet<UserRelationshipPreferences>();
            this.UserRelationships = new HashSet<UserRelationships>();
            this.UserRelationships1 = new HashSet<UserRelationships>();
            this.UserRoles = new HashSet<UserRoles>();
            this.UsersOnline = new HashSet<UsersOnline>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsSuperUser { get; set; }
        public Nullable<int> AffiliateId { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public bool UpdatePassword { get; set; }
        public string LastIPAddress { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> PasswordResetToken { get; set; }
        public Nullable<System.DateTime> PasswordResetExpiration { get; set; }
        public string LowerEmail { get; set; }
    
        public virtual ICollection<ContentWorkflowStatePermission> ContentWorkflowStatePermission { get; set; }
        public virtual ICollection<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual ICollection<DesktopModulePermission> DesktopModulePermission { get; set; }
        public virtual ICollection<FolderPermission> FolderPermission { get; set; }
        public virtual ICollection<ModulePermission> ModulePermission { get; set; }
        public virtual ICollection<PasswordHistory> PasswordHistory { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<Relationships> Relationships { get; set; }
        public virtual ICollection<TabPermission> TabPermission { get; set; }
        public virtual ICollection<UserAuthentication> UserAuthentication { get; set; }
        public virtual ICollection<UserPortals> UserPortals { get; set; }
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        public virtual ICollection<UserRelationshipPreferences> UserRelationshipPreferences { get; set; }
        public virtual ICollection<UserRelationships> UserRelationships { get; set; }
        public virtual ICollection<UserRelationships> UserRelationships1 { get; set; }
        public virtual ICollection<UserRoles> UserRoles { get; set; }
        public virtual ICollection<UsersOnline> UsersOnline { get; set; }
    }
}
