//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPGFL_WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendors
    {
        public Vendors()
        {
            this.Affiliates = new HashSet<Affiliates>();
            this.Banners = new HashSet<Banners>();
            this.VendorClassification = new HashSet<VendorClassification>();
        }
    
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public int ClickThroughs { get; set; }
        public int Views { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LogoFile { get; set; }
        public string KeyWords { get; set; }
        public string Unit { get; set; }
        public bool Authorized { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Cell { get; set; }
    
        public virtual ICollection<Affiliates> Affiliates { get; set; }
        public virtual ICollection<Banners> Banners { get; set; }
        public virtual Portals Portals { get; set; }
        public virtual ICollection<VendorClassification> VendorClassification { get; set; }
    }
}
